# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9655bd6b69976e93e718aedcd77d3c49d4b83270a97aca7a7d24ebcb88b3559447dd91e415540f545cd106ac38c404d94ccd7f3e4ecbf64d467f1f29e3ea7f03
  stripe_publishable_key: pk_test_hV7EXEeyOhLIgHCAMWxbIXv1
  stripe_secret_key: sk_test_gRbLcTnBldgs7Kh4Afo9SLPP

test:
  secret_key_base: 0c797a2231913e6928ddae43370eaee11dc6c548799e81a98ec54fe173aa5397cf96066822aa0aecefa48cfedee70b5d0902ff066afdcb2bee032fbe4ed7245c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
